
package cn.ws.client.user;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-22T12:15:06.003+08:00
 * Generated source version: 3.3.7
 *
 */
public final class UserService_UserServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.server.ws.cn", "UserService");

    private UserService_UserServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = UserService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        UserService_Service ss = new UserService_Service(wsdlURL, SERVICE_NAME);
        UserService port = ss.getUserServiceImplPort();

        {
        System.out.println("Invoking sayHello...");
        String _sayHello_username = "";
        String _sayHello__return = port.sayHello(_sayHello_username);
        System.out.println("sayHello.result=" + _sayHello__return);


        }

        System.exit(0);
    }

}
