package cn.ws.client.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-22T12:15:06.060+08:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://service.server.ws.cn", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @Action(input = "http://service.server.ws.cn/UserService/sayHelloRequest", output = "http://service.server.ws.cn/UserService/sayHelloResponse")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.server.ws.cn", className = "cn.ws.client.user.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.server.ws.cn", className = "cn.ws.client.user.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHello(

        @WebParam(name = "username", targetNamespace = "")
        String username
    );
}
